### ISSUE TITLE
请问能否把数字识别的训练集和测试集打包发上来？

### ISSUE THREAD

**Issue by qiuhez** [Jack-Cherish/Machine-Learning#13]

**Comment by Other-Side** [comment]
奇怪，我怎么收到了这个邮件，哈哈哈

**Comment by ActonMartin** [comment]
> 奇怪，我怎么收到了这个邮件，哈哈哈
是你点了watch

**Comment by qiuhez** [comment]
上面两位可以发给我吗?

**Comment by ActonMartin** [comment]
> 上面两位可以发给我吗?

邮箱留下

**Comment by ActonMartin** [comment]
> 上面两位可以发给我吗?
人家发了  存在这个目录
Machine-Learning/kNN/3.数字识别/trainingDigits/

**Comment by qiuhez** [comment]
aulotus8@163.com
非常感谢！

**Comment by Jack-Cherish** [comment]
@qiuhez 直接git clone https://github.com/Jack-Cherish/Machine-Learning  就都有了。。

**Comment by qiuhez** [comment]
好的，谢谢发自我的华为手机-------- 原始邮件 --------主题：Re: [Jack-Cherish/Machine-Learning] 请问能否把数字识别的训练集和测试集打包发上来？ (#13)发件人：Jack Cui 收件人：Jack-Cherish/Machine-Learning 抄送：qiuhez ,Mention @qiuhez 直接git clone https://github.com/Jack-Cherish/Machine-Learning就都有了。。
