### ISSUE TITLE
在你的博客机器学习实战中有一处问题

### ISSUE THREAD

**Issue by jccjd** [Jack-Cherish/Machine-Learning#14]
![2019-08-31 11-35-45屏幕截图](https://user-images.githubusercontent.com/29309532/64058818-89b70b00-cbe3-11e9-9058-4462d2e9c7b2.png)
在你的博客：机器学习实战教程（五）：朴素贝叶斯实战篇之新浪新闻分类中（https://cuijiahua.com/blog/2017/11/ml_5_bayes_2.html）
在对字符串转换成字符列表中用了`listOfTokens = re.split(r'\W*, bigString)`, 应该是`listOfTokens = re.split(r'\W+', bigString)`

最后造成分类的错误率达60%, 我看你`github`里的源码，是没有问题的，应该是笔者的手误

**Comment by Jack-Cherish** [comment]
@jccjd 已修改，感谢。
