### ISSUE TITLE
SVM算法中有个步骤不是很懂

### ISSUE THREAD

**Issue by lwd45** [Jack-Cherish/Machine-Learning#15]
在博主的svm-simple.py 文件中第 147 行
fXi = float(np.multiply(alphas,labelMat).T*(dataMatrix*dataMatrix[i,:].T)) + b
书上说fXi是我们预测的类别，我想问下为什么预测的类别是这样计算的？

**Comment by Jack-Cherish** [comment]
这是矩阵化的计算，如果一条数据一条数据的计算，可以用for循环。

**Comment by lwd45** [comment]
感谢博主，后来我在你的知乎账号上面找到了答案，再次感谢分享
