### ISSUE TITLE
关于SVM的一个问题

### ISSUE THREAD

**Issue by wwen101** [Jack-Cherish/Machine-Learning#16]

**Comment by pfzhang2022** [comment]
博主你好，我想问的问题是，这个迭代次数iter_num是不是说只要发现alpha有优化，迭代次数就从0开始重新计数；直到alpha在40次迭代内都没有优化，就可以认为alpha选取完成,我这么理解对吗？你发过来的邮件给我发了另一个问题，我在github和你的网站上也没有找到相应的语句，觉得很懵。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"9543211"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 凌晨0:39
收件人:&nbsp;"Jack-Cherish/Machine-Learning"<Machine-Learning@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Jack-Cherish/Machine-Learning] 关于SVM的一个问题 (#16)





 
在svm-smo.py中，if ((oS.labelMat[i] * Ei < -oS.tol) and (oS.alphas[i] < oS.C)) or ((oS.labelMat[i] * Ei &gt; oS.tol) and (oS.alphas[i] &gt; 0)):这个语句表示什么意思，一直没看明白？
