### ISSUE TITLE
错误率问题

### ISSUE THREAD

**Issue by xiaomintongxue** [Jack-Cherish/Machine-Learning#6]
按照您的思路和自己的结合写了约会那个测试，我的结果是8%错误率。怎么你的博客是3%？？然后我把你github这个程序拷贝直接运行，结果是4%。。咋回事？？？求解答谢谢啦

**Comment by Jack-Cherish** [comment]
数据集小，错误率有浮动很正常。

**Comment by xiaomintongxue** [comment]
很纳闷。同样的数据，同样设置的参数。按理计算出来的结果应该一样啊。除非我改了参数如变成测试200项，k值也变变，这样可能出现不一样的错误率。但是啥都一样为何还会出现不同呢？




发自网易邮箱大师
在2017年12月29日 11:19，Jack Cui 写道：

数据集下，错误率有浮动很正常。

**Comment by xiaomintongxue** [comment]
实在不好意思打扰了。是我的问题。有个地方没缩进了。导致有问题。现在和github是一致的。




发自网易邮箱大师
在2017年12月29日 11:29，xiaomintongxue 写道：
很纳闷。同样的数据，同样设置的参数。按理计算出来的结果应该一样啊。除非我改了参数如变成测试200项，k值也变变，这样可能出现不一样的错误率。但是啥都一样为何还会出现不同呢？




发自网易邮箱大师
在2017年12月29日 11:19，Jack Cui 写道：

数据集下，错误率有浮动很正常。
