### ISSUE TITLE
决策树最优特征

### ISSUE THREAD

**Issue by Demonya** [Jack-Cherish/Machine-Learning#7]
想问一下楼主，为什么初始的最优特征赋值为-1？可以赋值为其他值么？

**Comment by Jack-Cherish** [comment]
@Demonya 就是先给个不可能的值啊~  只要是负数就可以，0和正数不行，因为有特征表示。

**Comment by Demonya** [comment]
OK，谢谢楼主！！后面有问题再请教。。
